### ISSUE TITLE
Determining shared information

### ISSUE THREAD

**Issue by slargman** [FECTeamOne/Serum#115]
@hangyin2020 @zman811 I make the following calls to the  API:

- GET to /products/:product_id
- GET to /products/:product_id/styles

I also need the number of reviews for `:product_id` and the rating for `:product_id`

### Shared information
- GET to /products/:product_id
- GET to /products/:product_id/styles
- GET to /reviews/meta:id

**Comment by hangyin2020** [comment]
I make the following calls to the API:

- GET to /products/:product_id
- GET to /products
- GET to /products/:product_id/styles
- GET to /products/:product_id/related

I am working to add the following calls to the API:

- GET to /reviews/meta?product_id, and then I will get a response, from which
get the response.ratings, something similar to:
 "ratings": {
        "1": "61",
        "2": "57",
        "3": "146",
        "4": "118",
        "5": "308"
    }

and then loop through all ratings and calculate a value, for example, 4.2 then I will have <Stars value={4.2} />

**Comment by hangyin2020** [comment]
yup, I just found it in his Ratings, still learning what he is doing there haha

**Comment by zman811** [comment]
i send 
GET : reviews/meta:id, /products/productid and one to get the reviews which I don't think is shared or I could make shared anyways

**Comment by hangyin2020** [comment]
how about let me make it work on my end first and then we can talk about to share it tomorrow if we need to?
