### ISSUE TITLE
Star Rating

### ISSUE THREAD

**Issue by slargman** [FECTeamOne/Serum#18]
Each product has an average rating based on its reviews. The average rating of the product will be represented by an array of solid or outlined stars, where the number of solid stars represents the review score. A total of 5 stars should always appear. The number of stars filled in should correspond to the average score.

The visual for rating should be representative of up to a quarter of a review point. For example, if the average is 3.8, this should display as 3¾ solid stars and 1¼ outlined stars. 

Next to the star rating, a link stating “Read all [#] reviews” will show. The total number of reviews should be inserted in place of [#]. Clicking this link should scroll the page to the Ratings & Reviews module.

If there are no reviews, this entire section should be hidden.

**Comment by slargman** [comment]
@zman811 I think this will be relevant for your module too, right? My plan is to make a component `<Stars />` for general that would take the prop `rating`, e.g. `<Stars rating={3.686} />` would produce the appropriately rounded set of visual stars. I think you need the ability to have the stars be interactive in some cases too, correct? When writing a review the user should be able to hover over the stars to select the rating? To address that I think I'll have an additional optional prop `interactive` which would take a boolean indicating whether it should be static or not as well as an `onChange` prop that you could pass your change handler into from your parent form component. So overall the usage in that case would be something like:
```
<Stars  interactive={true} onChange={starsChangeHandler} />
```
Although maybe I can just assume that the Stars are meant to be interactive if no rating is passed. Would that address everything you need the stars for?

**Comment by zman811** [comment]
For sure we could share the noninteractive one or even only show it in one place. as for interaction I would need them to able to click a star and have it fill in up to where they clicked, if you think that can all put in one component that sounds great

**Comment by slargman** [comment]
I think it's better for you to handle the interactivity actually. I don't need it for my component since I only display a static set of stars. We can share the development for the non-interactive part if you want. I was thinking of creating `Stars` from 5 `Star` subcomponents which would handle the shading aspect. I can make `Star` and then you can take over and build it into `Stars` and deal with the interactive portion however you prefer.

**Comment by zman811** [comment]
Sure that sounds great, we can talk more once we start to make it as well
