### ISSUE TITLE
Decide design

### ISSUE THREAD

**Issue by slargman** [FECTeamOne/Serum#5]
- [x] #9 
- [x] Pull out the color scheme and typography
  - [x] Light and dark mode colors
- [x] Save pictures of design for reference

**Typography**
- body text: AdihausDIN
- slant caps: AdiahusDIN Cn
- bold: AdineuePRO

**Color Scheme**
- background: white #FFFFFF
- text: black #000000
- flip for dark mode

**Comment by zman811** [comment]
For the color scheme, we need a light and dark mode

**Comment by slargman** [comment]
### [adidas](https://www.adidas.com/us/badge-of-sport-tee/ED9610.html)

**Overview**
![Screen Shot 2022-05-18 at 4 10 22 PM](https://user-images.githubusercontent.com/16127198/169169973-cdea7599-e137-420b-8fab-214d5e4f01ac.png)
![Screen Shot 2022-05-18 at 4 10 29 PM](https://user-images.githubusercontent.com/16127198/169169983-6f9dd87b-e785-49e0-8f35-fb36b9a265c9.png)

**Ratings & Reviews**
![Screen Shot 2022-05-18 at 4 10 41 PM](https://user-images.githubusercontent.com/16127198/169169997-216ff3c0-3ddb-4ed1-80f6-c672ef3cb7ac.png)

**Related Items & Comparison**
![Screen Shot 2022-05-18 at 4 10 34 PM](https://user-images.githubusercontent.com/16127198/169169993-6d0f10d1-88fd-4dd0-91b9-398730ec847a.png)
