### ISSUE TITLE
Carousel

### ISSUE THREAD

**Issue by slargman** [FECTeamOne/Serum#54]
A general carousel component to capture the functionality needed in #44, #45, and #47. Should be at least take a prop to indicate how many child components should be displayed at a time and a prop consisting of an array of all the components that should appear in the carousel.

**Comment by hangyin2020** [comment]
of course,,actually I am searching around, let me know when you want to talk about it, I am ready all the time

**Comment by slargman** [comment]
Let's leave it for when we're moving on to development. I just finished setting up my ticket backlog and am going to take a look at getting our tests set up.

**Comment by hangyin2020** [comment]
sounds good, we can talk about it tomorrow
